# Generated by Django 3.0.5 on 2022-06-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
