# Generated by Django 4.2.3 on 2023-08-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_patient_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='visited',
        ),
    ]
